### ISSUE TITLE
Strange cartographer bug

### ISSUE THREAD

**Issue by Motschen** [valoeghese/TheBiomeOverhaul#2]
If I "upgrade" the level of an cartographer to apprentice,
something weird happens: I can't interact with anything, no entity moves and i can't save the world.
I tried every mod in my modpack and the mod that coursed this was TheBiomeOverhaul.
Strangely the log is just empty...

Here's a video that shows the bug:
https://youtu.be/VyOGCQXY-ac

**Comment by valoeghese** [comment]
I can't think why that would happen...

What other mods are you using?

**Comment by Motschen** [comment]
I tested it without all other mods, exept fabric-api and it crashed, without TheBiomeOverhaul it worked.

**Comment by valoeghese** [comment]
Someone said it could be to do with the maps they trade

**Comment by valoeghese** [comment]
Could you see if it could be because of the treasure maps? (by getting a map out of the creative inventory)

**Comment by valoeghese** [comment]
I'll look into this

**Comment by valoeghese** [comment]
```
java.io.FileNotFoundException: C:\TheBiomeOverhaul\run\.\saves\CartographyCrash\data\fabricRegistry.dat (The system cannot find the path specified)
	at java.io.FileOutputStream.open0(Native Method) ~[?:1.8.0_191]
	at java.io.FileOutputStream.open(Unknown Source) ~[?:1.8.0_191]
	at java.io.FileOutputStream.<init>(Unknown Source) ~[?:1.8.0_191]
	at java.io.FileOutputStream.<init>(Unknown Source) ~[?:1.8.0_191]
	at net.minecraft.world.WorldSaveHandler.handler$readWorldProperties$zcl000(WorldSaveHandler.java:602) [minecraft-1.14%20Pre-Release%204-mapped-2.jar:?]
	at net.minecraft.world.WorldSaveHandler.readProperties(WorldSaveHandler.java) [minecraft-1.14%20Pre-Release%204-mapped-2.jar:?]
	at net.minecraft.server.integrated.IntegratedServer.method_3735(IntegratedServer.java:68) [minecraft-1.14%20Pre-Release%204-mapped-2.jar:?]
	at net.minecraft.server.integrated.IntegratedServer.setupServer(IntegratedServer.java:94) [minecraft-1.14%20Pre-Release%204-mapped-2.jar:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:603) [minecraft-1.14%20Pre-Release%204-mapped-2.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
```

**Comment by valoeghese** [comment]
Not sure if that's it but it's an error anyway

**Comment by valoeghese** [comment]
Confirmed this is a bug

**Comment by valoeghese** [comment]
Nothing appears to apear in the log about this

**Comment by Motschen** [comment]
This really could be it... I found out that he wants to trade an Ocean Explorer Map...
Maybe MC has some problems with it becouse of the new biomes...
I don't think this can be fixed :(

**Comment by valoeghese** [comment]
I think I found something

**Comment by valoeghese** [comment]
There appears to be an infinite loop with sampling biomes

**Comment by valoeghese** [comment]
![2019-04-24_14 23 31](https://user-images.githubusercontent.com/46117728/56628133-c191cd00-669c-11e9-9c8c-2bb5bcd38f12.png)

@Motschen I changed how oceans generate ... 😄

**Comment by valoeghese** [comment]
It didn't freeze this time

**Comment by valoeghese** [comment]
It was freezing because of how long it's taking to locate the structure: the entire main thread is being devoted to locating the structure

**Comment by valoeghese** [comment]
![2019-04-24_14 29 43](https://user-images.githubusercontent.com/46117728/56628313-76c48500-669d-11e9-8952-afb976d66560.png)

The game froze for about 40 seconds finding the woodland mansion, and 2 finding the monument

**Comment by valoeghese** [comment]
It works now! Thanks for finding this bug!

**Comment by valoeghese** [comment]
Will upload a new version soon hopefully

**Comment by Motschen** [comment]
Thanks! Keep up the good work! :D

**Comment by valoeghese** [comment]
Do note the game will freeze for a few seconds still, howerver this should no longer be indefinite :)
